blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/boostcampaitech3/level2-object-detection-level2-cv-17/issues/new?template=issue_template.md
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://github.com/boostcampaitech3/level2-object-detection-level2-cv-17/issues/new?template=bug_report.md
    about: Please report security vulnerabilities here.
