blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: ?template=issue_template.md
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: ?template=bug_report.md
    about: Please report security vulnerabilities here.
    
